### ISSUE TITLE
Any phpmyadmin?

### ISSUE THREAD

**Issue by yangboz** [bitnami/bitnami-docker-mediawiki#62]
Any phpmyadmin service ?

**Comment by andrewhowdencom** [comment]
I think the answer to this both is, and should be, no. Normally we'd run this with the database separate, and in docker, the convention is "one logical service per container". If you need phpmyadmin, I think you'd best spin up another container pointed at the mariadb one that contains PHPMyAdmin.

**Comment by tompizmor** [comment]
Hello @yangboz,

As @andrewhowdencom proposes, you would run phpmyadmin in a separate container. The following docker-compose file should work for you:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '81:80'
      - '444:443'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  phpmyadmin_data:
    driver: local
```

Once it is deployed you could access MediaWiki at http://IP and phpMyAdmin at http://IP:81.

I hope it helps!
