### ISSUE TITLE
Admin rights.

### ISSUE THREAD

**Issue by lordSeaworth** [bitnami/bitnami-docker-mediawiki#69]
Am I missing something or why does the initial user created by the environmental variables on docker run not make it a sysop/bureaucrat? How do I make myself an sysop with this docker image?

**Comment by juan131** [comment]
Hi @lordSeaworth 

What actions were you unable to perform using the credentials you indicated using the env. variables: **MEDIAWIKI_USERNAME** & **MEDIAWIKI_PASSWORD**?

**Comment by lordSeaworth** [comment]
Access the admin section? Or any administration at all? Installing plugins. Adding users. Changing permissions. etc.... Seems the default user created with those environmental variables makes the user a normal user. Does not get added to the sysop or bureaucrat level.

**Comment by juan131** [comment]
Hi @lordSeaworth 

Could you try using the docker-compose below?

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=my-password
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_PORT_NUMBER=3306
      - REDMINE_DB_PASSWORD=my-password
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```
