### ISSUE TITLE
cannot connect to mysql database 

### ISSUE THREAD

**Issue by zhengyangfeng00** [bitnami/bitnami-docker-mediawiki#70]
**Description**

I have manually set up the bitnami mariadb container using docker bridge network, and I got this error when trying to manually bring up the mediawiki container:

```
Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to 127.0.0.1:3306 after 36 tries
```

**Steps to reproduce the issue:**

To completely replicate my setup is a bit complex, since I am using ansible to manage containers. But here are the relevant configs:

``` yaml
- name: ensure db user for mediawiki exists
  mysql_user:
    name: "{{ mediawiki_db_user }}"
    # host defines from which host the user's access is granted
    # this config value allows connection from any ip address
    host: "%"
    password: "{{ mediawiki_db_password }}"
    login_host: "{{ mariadb_host }}"
    login_port: "{{ mariadb_port }}"
    state: present
    priv: "{{ mediawiki_db }}.*:ALL"

- name: ensure mediawiki is running
  docker_container:
    name: mediawiki
    state: started
    image: bitnami/mediawiki:latest
    network_mode: bridge
    ports:
      - "{{ mediawiki_http_port }}:80"
    env:
      MARIADB_HOST: "172.17.0.1"
      MEDIAWIKI_DATABASE_PASSWORD: "{{ mediawiki_db_password }}"
      MEDIAWIKI_DATABASE_USER: "{{ mediawiki_db_user }}"
      MEDIAWIKI_DATABASE_NAME: "{{ mediawiki_db }}"
    volumes:
      - "{{ mediawiki_data_dir }}:/bitnami"
```

I have verified that the db is accessible from the container by first connecting to the media wiki container with `docker exec -it <container name> bash` and then use `mysql --user xxx --host 172.17.0.1 -p` to connect to the db.

I also verified with `docker inspect` that the mariadb_host environment variable is set on the container:

``` json
...
            "Env": [
                "MEDIAWIKI_DATABASE_USER=bn_mediawiki",
                "MEDIAWIKI_DATABASE_PASSWORD=qwerty123",
                "MARIADB_HOST=172.17.0.1",
                "MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki",
...
```

**Describe the results you received:**

```
...
Error executing 'postInstallation': Failed to connect to 127.0.0.1:3306 after 36 tries
```

**Describe the results you expected:**

I expect the db connection to success, at least it should try to connect to the db host I passed in(172.17.0.1), not 127.0.0.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
