### ISSUE TITLE
ERROR ==> The MARIADB_ROOT_PASSWORD environment variable is empty or not set

### ISSUE THREAD

**Issue by rosch100** [bitnami/bitnami-docker-mediawiki#81]
**Description**

Since the latest update, the container fails to start. The error is:
`The MARIADB_ROOT_PASSWORD environment variable is empty or not set`
This error shows despite the correct existing environment variable. When I set the environment variable `ALLOW_EMPTY_PASSWORD=yes`, the container tries to connect to the database without success (as expected).

**Additional information you deem important (e.g. issue happens only occasionally):**
docker-compose.yaml:
```
version: '3'
services:
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    container_name: wiki
    #    restart: unless-stopped
    environment:
      - MEDIAWIKI_WIKI_NAME=MyWiki
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=mypassword
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=wikidb
      - MYSQL_CLIENT_CREATE_DATABASE_USER=mywikiuser
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=mywikipassword
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=mywikiuser
      - MEDIAWIKI_DATABASE_NAME=wikidb
      - MEDIAWIKI_DATABASE_PASSWORD=mywikipassword
      - VIRTUAL_HOST=wiki.mydomain.de
    volumes:
      - '/srv/mediawiki:/bitnami/mediawiki'
    expose:
      - "80"
      - "443"
    dns:
      - 1.1.1.1
networks:
  default:
    external:
      name: nginx-proxy
```
**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 11
  Paused: 0
  Stopped: 1
 Images: 29
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1031-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.663GiB
 Name: docker
 ID: DCJT:4IXN:HFKB:4CQ3:6JTW:5CVA:AOQI:GEP6:34AH:6Q7K:N2PU:PAS3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
docker running in a HyperV Ubuntu VM

**Comment by dani8art** [comment]
Hi @rosch100 thanks for opening this issue, I saw you have used `ALLOW_EMPTY_PASSWORD=yes` but your docker-compose file has `MARIADB_ROOT_PASSWORD` set. 

Also, I'm trying in my local and I'm not able to reproduce it. 

Are you setting `ALLOW_EMPTY_PASSWORD=yes` in both containers?

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    image: 'docker.io/bitnami/mediawiki:1-debian-10'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_HOST=localhost:8080
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local

```
