### ISSUE TITLE
MediaWiki + Traefik 2.3.2 (bad gateway - GET / HTTP/1.1" 301)

### ISSUE THREAD

**Issue by KlugmannM** [bitnami/bitnami-docker-mediawiki#86]
Hello,

I tried to install on a VPS via docker-compose Mediawiki. The reverse proxy is Traefik which works with Nextcloud;Portainer without restrictions. Based on your template I have adapted the docker-compose.yml.

```
bitnami-docker-mediawiki 1.34.2-debian-10-r5 release
docker-compose version 1.25.4
traefik version v2.3.2
VPS Debian 10
```
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - '/opt/containers/mediawiki/mariadb_data:/bitnami/mariadb'
    networks:
      - default
  mediawiki:
    image: 'docker.io/bitnami/mediawiki:1-debian-10'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/containers/mediawiki/mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediawiki.entrypoints=http"
      - "traefik.http.routers.mediawiki.rule=Host(`####.eu`)"
      - "traefik.http.middlewares.mediawiki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mediawiki.middlewares=mediawiki-https-redirect"
      - "traefik.http.routers.mediawiki-secure.entrypoints=https"
      - "traefik.http.routers.mediawiki-secure.rule=Host(`####.eu`)"
      - "traefik.http.routers.mediawiki-secure.tls=true"
      - "traefik.http.routers.mediawiki-secure.tls.certresolver=http"
      - "traefik.http.routers.mediawiki-secure.service=mediawiki"
      - "traefik.http.services.mediawiki.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy
networks:
  proxy:
    external: true
```
So far everything could be installed without any problems, the containers run smoothly according to the logs.
If I now go to the given URL there is always badgateway.
[log_mediawiki](https://github.com/bitnami/charts/files/5538180/log_mediawiki.txt)

So when I change Port=80 to "traefik.http.services.mediawiki.loadbalancer.server.port=8080" i get the follwing

[log_Port8080_mediawiki.txt](https://github.com/bitnami/charts/files/5538210/log_Port8080_mediawiki.txt)

Do you have ideas or suggestions for a solution. Would be very grateful! I can't see the forest for the trees anymore.

**Comment by miguelaeh** [comment]
Hi @KlugmannM ,
>I had assumed that ports 8080 and 8443 were the default ports of the Mediawiki container.

That is correct, those are the ports used.

About traefik, I am afraid I am not familiar with it. I have take a look to your files but I can't see where is the `8080` indicated for mediawiki. 

Just to consider it, a `301` error is a `Moved Permanently` not sure how are you checking it but if you are using `curl` try adding the `-L`.

**Comment by KlugmannM** [comment]
Okay now it works. After a new installation and **PORT 8080** the following appears after entering your domain.
`https://localhost/wiki/Main_Page. ` after this you had to type for localhost your Domain (DNS) and then you had exis to your own mediawiki.

**Comment by andresbono** [comment]
That's great to hear! 🎉 Thanks for sharing what finally worked for you.

**Comment by wgandhi** [comment]
I am having the same issue described here.. When I get to <my-ip>:8080, the link is re-routed to localhost/wiki/Main_Page. I have to change localhost to <my-ip>:8080/wiki/Main_Page every single time for it to work. If I modify a wiki, I end up with the same issue. I tried modifying the env variable called MEDIAWIKI_HOST but that did not fix the issue, I always get routed to localhost.

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml file you are using?

**Comment by wgandhi** [comment]
I do not use docker-compose.. I followed the instructions from the wiki in this section  **Mount host directories as data volumes using the Docker command line**

Everything works fine, it is just difficult to keep changing ''localhost'' to ''my-ip:8080'' all the time.

**Comment by javsalgar** [comment]
Could you try launching a fresh instance (without re-using the previous volume, but creating a new one) and setting the MEDIAWIKI_HOST env var? Because this host is only set the first time.

**Comment by wgandhi** [comment]
that worked for the MEDIAWIKI_HOST, Thanks.
However, it does not append the port number correctly when I get re-directed to the main page.
I get the correct host but have to add the port number as a fix like before. I tried to use this env variable:MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER on a fresh volume. That did not help. Any other suggestions?

**Comment by wgandhi** [comment]
Added the external http port on a fresh instance. Is that the correct variable to use to specify the port?

**Comment by javsalgar** [comment]
I think so. Could you provide me the exact command you used for creating instance?

**Comment by MajorDisaster** [comment]
Hi, I'm having the same problem, it costed me a half day to find this simple solution. Following README.md:

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-mediawiki/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

then `localhost:8080` reroutes me to localhost/wiki/Main_Page, which gives me
_Not Found
HTTP Error 404. The requested resource is not found._

I have to change it to **http://localhost:8080/wiki/Main_Page** every time to get to the main page. What is the permanent solution? Thank you!

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    image: docker.io/bitnami/mediawiki:latest
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```

**Comment by MajorDisaster** [comment]
this didn't help MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080

**Comment by javsalgar** [comment]
Hi,

I tried to reproduce your instructions and found no issues. By default it is routing 80 -> 8080.

![image](https://user-images.githubusercontent.com/1133777/115356456-f8cbe380-a1bb-11eb-9334-2d4ae3262d6b.png)


Are you also using Traefik?

**Comment by MajorDisaster** [comment]
Hi, 

thanks, that is interesting.

I can't use port 80, so I'm binding 8080:8080
> Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions

No, I'm not using Traefik, just plain and simple containers and following readme.md

![image](https://user-images.githubusercontent.com/46490440/115556735-faaaab00-a27e-11eb-987f-d368332b36ff.png)

**Comment by javsalgar** [comment]
Hi,

In that screenshot, wouldn't the :8080 port be missing?

**Comment by wgandhi** [comment]
the missing port number is exactly the issue.. I can hand type the port number and make the wiki work.. The moment I make any edits, it goes back to localhost/wiki/Main_page

**Comment by MajorDisaster** [comment]
@wgandhi: correct, this is exactly the buggy behavior I'm observing: it always redirect you to localhost/wiki/Main_page and gives you Not Found error. 

It seems to work for @javsalgar though in the screenshot about, but didn't work for us

**Comment by javsalgar** [comment]
Hi, I use this docker-compose and it worked for me in port 8080

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    image: docker.io/bitnami/mediawiki:latest
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```
