### ISSUE TITLE
the page was always redirect to port 80 even I set MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER to 8080

### ISSUE THREAD

**Issue by wyntau** [bitnami/bitnami-docker-mediawiki#91]
**Description**

**Steps to reproduce the issue:**

1. `docker-compose up` to start mediawiki and mariadb service(docker-compose.yml see below)
2. visit http://localhost:8080

**Describe the results you received:**

the page was always redirect to http://localhost/wiki/Main_Page.

**Describe the results you expected:**

the page was correctly shown in http://localhost:8080/wiki/Main_Page

**Additional information you deem important (e.g. issue happens only occasionally):**

I tested both in docker desktop for mac and docker desktop for windows in WSL2 , it has the same problem.
When I use offical mediawiki:1.35.2 docker image, it works well.

**docker-compose.yml**
```yml
version: '3'

services:
  mediawiki:
    image: bitnami/mediawiki:1.35.2
    restart: always
    networks:
      - mediawiki
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_DATABASE_USER=mediawiki
      - MEDIAWIKI_DATABASE_PASSWORD=Pa5swd
      - MEDIAWIKI_DATABASE_NAME=mediawiki
      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080
      - MEDIAWIKI_EXTERNAL_HTTPS_PORT_NUMBER=8443
    volumes:
      - ./mediawiki-data:/bitnami/mediawiki
  mariadb:
    image: bitnami/mariadb
    container_name: mariadb
    restart: always
    networks:
      - mediawiki
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=mediawiki
      - MARIADB_PASSWORD=Pa5swd
      - MARIADB_DATABASE=mediawiki
    volumes:
      - ./mariadb-data:/bitnami/mariadb
networks:
  mediawiki:
```

**Version**

- Output of `docker version`:

```shell
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: XFPP:AKPR:ZKLX:QJKP:MHIO:45FW:JNWI:WT4W:MWRS:UURB:AZBJ:TQ5H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```shell
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by migruiz4** [comment]
Hi @wyntau ,

Thank you for reporting this issue.

There is a bug where the variables `MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER`, `MEDIAWIKI_EXTERNAL_HTTPS_PORT_NUMBER`, and `MEDIAWIKI_ENABLE_HTTPS` were not being taken into account.
A new version of the bitnami/mediawiki image fixing this issue will be released soon.

Meanwhile, as a workaround, you could use `MEDIAWIKI_HOST=localhost:8080` to fix the redirection issue.

**Comment by wyntau** [comment]
Thanks very much. waiting for the new version image 😃

**Comment by migruiz4** [comment]
Hi @wyntau,

A new version of the MediaWiki image has been released including a fix for your issue: `1.35.2-debian-10-r14`.

Let me know if it worked for you.

**Comment by wyntau** [comment]
Thank you very much. It works now. 😃

**Comment by danielmenezesbr** [comment]
Hi @migruiz4, 1.35.2-debian-10-r14 or workaround doesn't work for me.

docker-compose.yml

```
version: '2'
services:
  mariadb:
    restart: always
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    restart: always
    image: docker.io/bitnami/mediawiki:1.35.2-debian-10-r14
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_HOST=localhost:8080
      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```

$ wget 127.0.0.1:8080

```
--2021-04-30 13:35:11--  http://127.0.0.1:8080/
Connecting to 127.0.0.1:8080... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://localhost/wiki/Main_Page [following]
--2021-04-30 13:35:17--  http://localhost/wiki/Main_Page
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
```

I also tried to remove MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER but the result was the same

**Comment by migruiz4** [comment]
Hi @danielmenezesbr,

Could you try using the following docker-compose?

```
version: '2'
services:
  mariadb:
    restart: always
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    restart: always
    image: docker.io/bitnami/mediawiki:1.35.2-debian-10-r14
    ports:
      - '8080:8080' <-- You were listening on Docker host port 80
      - '443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_HOST=localhost <-- Don't add port number here
      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```

Then, from your docker host, try running `wget localhost:8080`
```
$ wget localhost:8080
--2021-04-30 14:22:01--  http://localhost:8080/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://localhost:8080/wiki/Main_Page [following]
--2021-04-30 14:22:01--  http://localhost:8080/wiki/Main_Page
Reusing existing connection to localhost:8080.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                         [ <=>                                                                                                 ]  14.80K  --.-KB/s    in 0s      

2021-04-30 14:22:02 (246 MB/s) - ‘index.html’ saved [15153]
```

The workaround I mentioned is for images prior to `1.35.2-debian-10-r14` and won't work after the fix.
