### ISSUE TITLE
Can't remove /wiki path prefix

### ISSUE THREAD

**Issue by wyntau** [bitnami/bitnami-docker-mediawiki#92]
**Description**

I want to remove the `/wiki` path prefix, so I change `$wgArticlePath = "/wiki/$1";` to `$wgArticlePath = "/$1";`

**Steps to reproduce the issue:**

1. change `$wgArticlePath = "/wiki/$1";` to `$wgArticlePath = "/$1";`
2. `docker-compose up`

**Describe the results you received:**
the page show  not found
![image](https://user-images.githubusercontent.com/2631733/115409037-f7ce9c80-a223-11eb-99f0-f7e68c7106c4.png)

**Describe the results you expected:**

the page was shown correctly without the `/wiki` prefix.
I found docker env `MEDIAWIKI_WIKI_PREFIX`, so I set it to empty, and **it not work**.
I checked the docker container, found `/opt/bitnami/apache/conf/vhosts/mediawiki-vhost.conf` contains `RewriteRule ^/?wiki(/.*)?$ %{DOCUMENT_ROOT}/index.php [L]`, so I change `MEDIAWIKI_WIKI_PREFIX` to `MEDIAWIKI_WIKI_PREFIX=/`, **it also not work**.

Can you help me how can I remove the `/wiki` path prefix?

**Additional information you deem important (e.g. issue happens only occasionally):**
my docker-compose.yml
```yml
version: '3'

services:
  mediawiki:
    image: bitnami/mediawiki:1.35.2
    restart: always
    networks:
      - mediawiki
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MEDIAWIKI_WIKI_NAME=SelfWiki
      - MEDIAWIKI_WIKI_PREFIX=

      - MEDIAWIKI_DATABASE_USER=mediawiki
      - MEDIAWIKI_DATABASE_PASSWORD=Pa5swd
      - MEDIAWIKI_DATABASE_NAME=mediawiki

      - MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=8080
      - MEDIAWIKI_EXTERNAL_HTTPS_PORT_NUMBER=8443
      - MEDIAWIKI_HOST=localhost:8080
    volumes:
      - ./mediawiki-data:/bitnami/mediawiki
  mariadb:
    image: bitnami/mariadb
    container_name: mariadb
    restart: always
    networks:
      - mediawiki
    environment:
      - MARIADB_ROOT_PASSWORD=Pa5swd@root
      - MARIADB_USER=mediawiki
      - MARIADB_PASSWORD=Pa5swd
      - MARIADB_DATABASE=mediawiki
    volumes:
      - ./mariadb-data:/bitnami/mariadb
networks:
  mediawiki:
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 3.84GiB
 Name: docker-desktop
 ID: TTNJ:PEQF:2PQY:KIAY:H4AO:QIHD:3GER:DZ35:LPJN:PSYS:DPZR:KDQR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
