### ISSUE TITLE
Failed to enable SSL for custom-domain

### ISSUE THREAD

**Issue by fo0** [bitnami/bitnami-docker-mediawiki#95]
**Description**

I can't activate ssl cert for the mediawiki. I am using the docker-compose install instructions including all the instructions for ssl

**Steps to reproduce the issue:**

1. download and modify docker-compose https://github.com/bitnami/bitnami-docker-mediawiki#tldr
```bash
$ cd /root/
$ wget https://raw.githubusercontent.com/bitnami/bitnami-docker-mediawiki/master/docker-compose.yml
```

2. prepare ssl: https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates I am using letsencrypt to create the cert. 
```bash
create letsencrypt ... output:
$ ls letsencrypt cert 
cert.pem  chain.pem  fullchain.pem  privkey.pem

$ mkdir /root/certs # folder to store certs
$ cp letsencrypt/fullchain.pem /root/certs/server.crt
$ cp letsencrypt/privkey.pem /root/certs/server.key
```

3. modify docker-compose according to your guides: https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

```yml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    image: docker.io/bitnami/mediawiki:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MEDIAWIKI_ENABLE_HTTPS=yes # SSL
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
      - /root/certs:/certs # SSL
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```

4. starting via docker-compose
```bash
docker-compose up
```

**Describe the results you received:**

ERROR 

```log
mariadb_1    | 2021-04-30 21:02:15 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1    | Version: '10.3.28-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mediawiki_1  | mediawiki 21:02:23.34 INFO  ==> ** MediaWiki setup finished! **
mediawiki_1  | 
mediawiki_1  | mediawiki 21:02:23.36 INFO  ==> ** Starting Apache **
mediawiki_1  | [Fri Apr 30 21:02:23.430978 2021] [ssl:emerg] [pid 1] (13)Permission denied: AH02574: Init: Can't open server private key file /opt/bitnami/apache/conf/bitnami/certs/server.key
mediawiki_1  | [Fri Apr 30 21:02:23.431507 2021] [ssl:emerg] [pid 1] AH02312: Fatal error initialising mod_ssl, exiting.
mediawiki_1  | [Fri Apr 30 21:02:23.431772 2021] [ssl:emerg] [pid 1] AH02564: Failed to configure encrypted (?) private key www.example.com:8443:0, check /opt/bitnami/apache/conf/bitnami/certs/server.key
mediawiki_1  | AH00016: Configuration Failed
```

**Describe the results you expected:**

Mediawiki is up and running with SSL... AND using my domain from the SSL cert (i tried it with custom host / virtual host but also didn't work!)

Without the SSL, it works as expected

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.8, build afacb8b7f0
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.34-1-pve
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 512MiB
 Name: wiki
 ID: EFJO:4RWX:O62O:PQKO:ELSE:U4XZ:JWPK:BH7D:RG5N:XOX3:NVAY:PEW5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
proxmox
