### ISSUE TITLE
Using AWS EFS mount for uploads 

### ISSUE THREAD

**Issue by rednevals** [bitnami/bitnami-docker-mediawiki#99]
**Description**
I have been looking for detailed examples for creating a mount point in my Mediawiki container, pointing to an AWS EFS drive. There are descriptions of setting the proper values in LocalSettings.php:

  $wgUploadPath
  $wgUploadDirectory

Can someone direct me to any examples of creating the mount?

**Comment by carrodher** [comment]
In a generic way, you can mount volumes if you are using the docker-compose as described in this README section (https://github.com/bitnami/bitnami-docker-mediawiki#persisting-your-application). In the same way, if you are using the Helm Chart there are `extraVolumeMounts` and `extraVolumes` parameters to configure this part of the persistence, you can take a look at the related parameters at https://github.com/bitnami/charts/tree/master/bitnami/mediawiki#mediawiki-deployment-parameters

I am not sure about what is the relation between the volumes and the PHP file

**Comment by rednevals** [comment]
What I'm looking for is the '/path/to/' for the Docker Compose. I have created the EFS filesystem in AWS, and have the ID. This discussion seems to indicate that it is possible, but I was looking for a full-up working example:

https://www.mediawiki.org/wiki/Topic:Uylkzx6gd2r0xoea

I love how they say that is works "out-of-the-box". Where is this documented? I'm just missing a couple of piece of the puzzle.

**Comment by carrodher** [comment]
The path should be the same that is used right now in the docker-compose:
https://github.com/bitnami/bitnami-docker-mediawiki/blob/605e4f9bb2325c9e4dfcd72e64cdeddc3d63b129/docker-compose.yml#L23

In the case of the existing docker-compose, there are defined two local volumes (one for the database and another one for mediawiki) and then those volumes are attached to the containers in a specific path:
```yaml
version: '2'
services:
  mariadb:
    ..
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    ...
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
...
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
```

If you want to replace the local volume defined by default by any other you should change the `volumes:` section. You can find more information about persistence in the following link: https://github.com/bitnami/bitnami-docker-mediawiki#persisting-your-application

Apart from that, I don't know how the extension you mentioned works, it seems like a third-party extension. We (from Bitnami) package the opensource application (MediaWiki in this case) and distribute it in different flavors such as containers, Helm Charts, VMs, local installers, etc but we don't develop nor provide support about specific plugins/extensions or consulting services for deploying the solutions in very specific scenarios; in that case, maybe you can find more information in the MediaWiki forums or support channels

**Comment by rednevals** [comment]
I am not using that extension. This was just one of the discussions I could find about using existing EFS for storage. My question was related to how to specify the path correctly. This is most likely from my inexperience with Docker. 

When I work locally, Docker creates the volumes and they are populated the first time the stack comes up. As I understand things, when the context is changed to AWS it will do the same after creating the EFS storage necessary. The Docker Compose file does not need to change. What I was trying to understand, what if I wanted to use different/existing storage in AWS. How would I configure that in the compose file in a way that would allow it to work both locally and in AWS. This might not be possible. Just looking for some clarity...

For example, I could specify the volume as external this way:

<pre>
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    external: true
    name: "fs-dff2966b"
</pre>

That name is the existing EFS filesystem.

**Comment by carrodher** [comment]
Maybe you can try mounting two different volumes (the local and the AWS one) in the same path, something like:
```
version: '2'
services:
  mariadb:
    ..
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  mediawiki:
    ...
    volumes:
      - 'mediawiki_data:/bitnami/mediawiki'
      - 'mediawiki_data_aws:/bitnami/mediawiki'
...
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  mediawiki_data_aws:
    external: true
    name: "fs-dff2966b"
```

I'm not sure if you can find any issue because the mounting point is the same for both volumes so there can be some conflicts.
